<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='css/todo.css' rel="stylesheet" type="text/css">
    </head>
    <body>
        <h1>Blue Todo</h1>
        <form method="post">
            <ul>
                <?php
                   echo \Todo\ViewHelpers\TaskListHelper::ListTasks($tasklist->getTasks());
                ?>
                <li>
                    <input name="new_task" type="text" placeholder="Enter a new task here...">
                </li>
            </ul>
            <input type="submit" value="SUBMIT">
        </form>
    </body>
</html>
